controllers/ArticleController.php
<?php

namespace app\controllers;

use app\models\ArticlesTags;
use app\models\Tags;
use app\models\Users;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\Article;
use app\models\EntryForm;

class ArticleController extends Controller
{
    public function actionIndex()
    {
        $query = Article::find();

        $pagination = new Pagination([
            'defaultPageSize' => 8,
            'totalCount' => $query->count(),
        ]);

        $articles = $query
            ->with('user')
            ->with('tags')
            ->orderBy('heading')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

//        print_r($articles[16]->tags[0]->tagName); exit;

        return $this->render('index', [
            'articles' => $articles,
            'pagination' => $pagination,
        ]);
    }


    public function actionEntry()
    {
        $model = new EntryForm();
        $cookies = Yii::$app->request->cookies;
        $user_id = $cookies['id'];
        $user = Users::findOne($user_id);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $article = new Article();
            $article->heading = $model->heading;
            $article->message = $model->message;
            $user->link('articles', $article);

            $tags = explode(',', $model->tags);

            foreach ($tags as $tag) {
                $tag = trim($tag);
                $oneTag = Tags::findOne(['tag_name' => $tag]);
                if(!$oneTag){
                    $oneTag = new Tags();
                    $oneTag->tag_name = $tag;
                    $oneTag->save();
                }

                $artTeg = new ArticlesTags();
                $artTeg->article_id = $article->id;
                $artTeg->tag_id = $oneTag->tag_id;
                $artTeg->save();
            }

            return $this->render('entry-confirm', ['model' => $model]);
        } else {
            // либо страница отображается первый раз, либо есть ошибка в данных
            return $this->render('entry', ['model' => $model]);
        }
    }

    public function actionDelete($id)
    {
        $article = Article::findOne($id);
        $article->delete();
        return $this->goBack();
    }

    public function actionEdit($id)
    {
        $article = Article::findOne($id);
        return $this->render('entry', ['model' => $article]);

    }

    public function actionUpdate($id)
    {
        $params = Yii::$app->request->post();

        $article = Article::findOne($id);
        $article->heading = $params['Article']['heading'];
        $article->message = $params['Article']['message'];
        $article->update();
        $this->redirect('/article');
    }

    public function actionSearch()
    {

        $strSearch = Yii::$app->request->post()['search'];
        $postSearch = $strSearch;
        $strSearch = explode(' ', $strSearch);

        foreach ($strSearch as $key => $row) {
            $strSearch[$key] = '*' . $row . '*';
        }

        $strSearch = implode(' ', $strSearch);

        $articles = Article::find()
            ->where('match(heading, message) against ("' . $strSearch . '" IN BOOLEAN MODE)');

        $provider = new ActiveDataProvider([
            'query' => $articles,
            'pagination' => [
                'pageSize' => 2
            ]
        ]);

        return $this->render('search', compact(['articles', 'provider', 'postSearch']));
    }

    public function actionTagSearch($tag)
    {
        $articles = Article::find()
            ->leftJoin('tags', 'tags.tag_name = "' . $tag . '"')
            ->leftJoin('articles_tags', 'articles_tags.tag_id = tags.tag_id')
            ->where('articles.id = articles_tags.article_id')->all();

        $pagination = new Pagination([
            'defaultPageSize' => 8,
            'totalCount' => count($articles),
        ]);
        return $this->render('index', compact('articles', 'pagination'));
    }
}

controllers/UsersController.php
<?php

namespace app\controllers;

use app\models\Users;
use Yii;
use yii\web\Controller;
use app\models\LoginForm;
use app\models\UsersForm;

class UsersController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionReg()
    {
        $model = new UsersForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            // данные в $model удачно проверены
            $user = new Users();
            $user->name = $model->name;
            $user->password = md5($model->password);
            $user->authKey = 1;
            $user->accessToken = 1;
            $user->save();

            return $this->render('gut-reg', ['model' => $model]);
        } else {
            // либо страница отображается первый раз, либо есть ошибка в данных
            return $this->render('form-reg', ['model' => $model]);
        }
    }


    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();

        #<form>
        $form = Yii::$app->request->post();
        $name = $form['LoginForm']['name'];
        $password = md5($form['LoginForm']['password']);

        #data base
        $user = Users::findOne(['name' => $name]);

        if ($user->name == $name && $user->password == $password) {

            $hash = md5($this->generateCode());

            // получение коллекции (yii\web\CookieCollection) из компонента "response"
            $cookies = Yii::$app->response->cookies;
            // добавление новой куки
                $cookies->add(new \yii\web\Cookie([
                    'name' => 'id',
                    'value' => $user->id,
                ]));
                $cookies->add(new \yii\web\Cookie([
                    'name' => 'name',
                    'value' => $name,
                ]));
                $cookies->add(new \yii\web\Cookie([
                    'name' => 'hash',
                    'value' => $hash,
                ]));

            //запись в базу
            $user->authKey = $hash;
            $user->save();

            return $this->goBack();
        } else
            return $this->render('login', ['model' => $model]);

    }

    # Функция для генерации случайной строки
    public function generateCode($length = 6)
    {
        $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHI JKLMNOPRQSTUVWXYZ0123456789";
        $code = "";
        $clen = strlen($chars) - 1;
        while (strlen($code) < $length) {
            $code .= $chars[mt_rand(0, $clen)];
        }
        return $code;
    }

    public function actionLogout()
    {
        // получение коллекции (yii\web\CookieCollection) из компонента "response"
        $cookies = Yii::$app->response->cookies;
        // удаление куки...
        $cookies->remove('name');
        $cookies->remove('hash');
        return $this->goBack();
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    // получение коллекции кук (yii\web\CookieCollection) из компонента "request"
    $cookies = Yii::$app->request->cookies;
    $name = $cookies['name'];

    if(isset($name)){
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => [
                ['label' => 'Articles', 'url' => ['/article/index']],
                ['label' => 'Registration', 'url' => ['/users/reg']],
                ['label' => 'Logout ('. $name.')' , 'url' => ['/users/logout']]
            ]]);

        NavBar::end();
    }else{
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => [
                ['label' => 'Articles', 'url' => ['/article/index']],
                ['label' => 'Registration', 'url' => ['/users/reg']],
                ['label' => 'Login' , 'url' => ['/users/login']],
            ]]);

        NavBar::end();
    }
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>